#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

#include "log.h"
#include "nat.h"
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	//fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	DEBUG_PRINT printf("Longest match ip: "IP_FMT"\n", HOST_IP_FMT_STR(dst));
	DEBUG_PRINT print_rtable();
	rt_entry_t *entry = NULL, *match = NULL;
	list_for_each_entry(entry, &rtable, list){
		if ((entry->dest & entry->mask) == (dst & entry->mask))
			if (!match || entry->mask > match->mask)
				match = entry;
	}
	return match;
}

// forward the IP packet from the interface specified by longest_prefix_match, 
// when forwarding the packet, you should check the TTL, update the checksum,
// determine the next hop to forward the packet, then send the packet by 
// iface_send_packet_by_arp
void ip_forward_packet(u32 ip_dst, char *packet, int len)
{
	//fprintf(stderr, "TODO: forward ip packet.\n");
	DEBUG_PRINT printf("\nBegin ip forward packet.\n");
	//find the iface
	rt_entry_t *entry = longest_prefix_match(ip_dst);
	if (!entry) {
		//log(ERROR, "Could not find forwarding rule for IP (dst:"IP_FMT") packet.", 
		//		HOST_IP_FMT_STR(ip_dst));
		icmp_send_packet(packet, len, ICMP_DEST_UNREACH, ICMP_NET_UNREACH);
		return ;
	}

	//check the TTL
	struct iphdr *ip_hdr = packet_to_ip_hdr(packet);
	u8 ttl = ip_hdr->ttl;
	DEBUG_PRINT printf("The TTL of packet is %d.\n", ttl);
	if (ttl <= 1){
		//log(ERROR, "IP packet TTL is zero.");
		icmp_send_packet(packet, len, ICMP_TIME_EXCEEDED, 0);
		return ;
	}
	else 	
		ip_hdr->ttl -= 1;

	//update the checksum
	ip_hdr->checksum = ip_checksum(ip_hdr);

	//determine the next hop to forward the packet
	u32 next_hop = entry->gw;
	if (!next_hop)
		next_hop = ip_dst;
	DEBUG_PRINT printf("Next hop ip: "IP_FMT"\n", HOST_IP_FMT_STR(next_hop));
	//send the packet
	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);	
}

// handle ip packet
//
// If the packet is ICMP echo request and the destination IP address is equal to
// the IP address of the iface, send ICMP echo reply; otherwise, forward the
// packet.
void handle_ip_packet(iface_info_t *iface, char *packet, int len)
{
	//fprintf(stderr, "TODO: handle ip packet: echo the ping packet, and forward other IP packets.\n");
	DEBUG_PRINT printf("\nBegin handle IP packet.\n");
	struct iphdr *ip_hdr = (struct iphdr *)packet_to_ip_hdr(packet);
	struct icmphdr *icmp_hdr = (struct icmphdr *)IP_DATA(ip_hdr);
	DEBUG_PRINT printf("The IP protocol: %d\tICMP flag is: %d\n",ip_hdr->protocol, IPPROTO_ICMP);
	DEBUG_PRINT printf("IP packet source ip: "IP_FMT"\tIP packet dest ip: "IP_FMT"\n", NET_IP_FMT_STR(ip_hdr->saddr), NET_IP_FMT_STR(ip_hdr->daddr));
	DEBUG_PRINT printf("Local iface ip: "IP_FMT"\n", HOST_IP_FMT_STR(iface->ip));
	if (ip_hdr->protocol == IPPROTO_ICMP && icmp_hdr->type == ICMP_ECHOREQUEST && ntohl(ip_hdr->daddr) == iface->ip)
		icmp_send_packet(packet, len, ICMP_ECHOREPLY, 0);
	else
		nat_translate_packet(iface, packet, len);
}

// send IP packet
//
// Different from ip_forward_packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	DEBUG_PRINT printf("\nBegin ip send packet.\n");
	struct iphdr *ip = packet_to_ip_hdr(packet);
	u32 dst = ntohl(ip->daddr);
	DEBUG_PRINT printf("Packet dest ip: "IP_FMT"\n", HOST_IP_FMT_STR(dst));
	rt_entry_t *entry = longest_prefix_match(dst);
	if (!entry) {
		//log(ERROR, "Could not find forwarding rule for IP (dst:"IP_FMT") packet.", 
		//		HOST_IP_FMT_STR(dst));
		free(packet);
		return ;
	}

	u32 next_hop = entry->gw;
	if (!next_hop)
		next_hop = dst;
	DEBUG_PRINT printf("Next hop ip: "IP_FMT"\n", HOST_IP_FMT_STR(next_hop));
	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
}
